BEGIN;

SET search_path TO public;

CREATE TYPE user_role AS ENUM (
  'STUDENT',
  'TEACHER',
  'ADMIN'
);

CREATE TYPE attendance_status AS ENUM (
  'HADIR',
  'TERLAMBAT',
  'TIDAK_HADIR'
);

CREATE TABLE education_levels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_education_levels PRIMARY KEY (id),
  CONSTRAINT uq_education_levels_name UNIQUE (name)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  email_verified_at TIMESTAMPTZ(6),
  password VARCHAR(255) NOT NULL,
  role user_role NOT NULL,
  phone VARCHAR(30),
  birth_date DATE,
  remember_token VARCHAR(100),
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_role ON users (role);

CREATE TABLE student_profiles (
  user_id BIGINT NOT NULL,
  student_number VARCHAR(50) NOT NULL,
  education_level_id BIGINT NOT NULL,
  CONSTRAINT pk_student_profiles PRIMARY KEY (user_id),
  CONSTRAINT uq_student_profiles_student_number UNIQUE (student_number),
  CONSTRAINT fk_student_profiles_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_student_profiles_education_level
    FOREIGN KEY (education_level_id)
    REFERENCES education_levels (id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_student_profiles_education_level
  ON student_profiles (education_level_id);

CREATE TABLE teacher_profiles (
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_teacher_profiles PRIMARY KEY (user_id),
  CONSTRAINT fk_teacher_profiles_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE TABLE classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  education_level_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_classes PRIMARY KEY (id),
  CONSTRAINT uq_classes_education_level_name UNIQUE (education_level_id, name),
  CONSTRAINT fk_classes_education_level
    FOREIGN KEY (education_level_id)
    REFERENCES education_levels (id)
    ON DELETE RESTRICT
);

CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(150) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_subjects PRIMARY KEY (id),
  CONSTRAINT uq_subjects_name UNIQUE (name)
);

CREATE TABLE class_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  class_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_class_students PRIMARY KEY (id),
  CONSTRAINT fk_class_students_class
    FOREIGN KEY (class_id)
    REFERENCES classes (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_class_students_student
    FOREIGN KEY (student_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_class_students_active_student
  ON class_students (student_id)
  WHERE is_active;

CREATE INDEX idx_class_students_student_active
  ON class_students (student_id, is_active);

CREATE INDEX idx_class_students_class_active
  ON class_students (class_id, is_active);

CREATE TABLE teacher_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  teacher_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_teacher_assignments PRIMARY KEY (id),
  CONSTRAINT uq_teacher_assignments_id_class UNIQUE (id, class_id),
  CONSTRAINT fk_teacher_assignments_teacher
    FOREIGN KEY (teacher_id)
    REFERENCES users (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_teacher_assignments_class
    FOREIGN KEY (class_id)
    REFERENCES classes (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_teacher_assignments_subject
    FOREIGN KEY (subject_id)
    REFERENCES subjects (id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_teacher_assignments_active_assignment
  ON teacher_assignments (teacher_id, class_id, subject_id)
  WHERE is_active;

CREATE INDEX idx_teacher_assignments_teacher_active
  ON teacher_assignments (teacher_id, is_active);

CREATE INDEX idx_teacher_assignments_class_active
  ON teacher_assignments (class_id, is_active);

CREATE INDEX idx_teacher_assignments_subject_active
  ON teacher_assignments (subject_id, is_active);

CREATE TABLE attendance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  assignment_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  session_date DATE NOT NULL,
  start_at TIMESTAMPTZ(6) NOT NULL,
  end_at TIMESTAMPTZ(6) NOT NULL,
  qr_payload VARCHAR(255) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_attendance_sessions PRIMARY KEY (id),
  CONSTRAINT uq_attendance_sessions_qr_payload UNIQUE (qr_payload),
  CONSTRAINT uq_attendance_sessions_assignment_date_time
    UNIQUE (assignment_id, session_date, start_at, end_at),
  CONSTRAINT chk_attendance_sessions_time CHECK (end_at > start_at),
  CONSTRAINT fk_attendance_sessions_assignment_class
    FOREIGN KEY (assignment_id, class_id)
    REFERENCES teacher_assignments (id, class_id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_sessions_class
    FOREIGN KEY (class_id)
    REFERENCES classes (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_sessions_created_by
    FOREIGN KEY (created_by)
    REFERENCES users (id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_attendance_sessions_assignment_time
  ON attendance_sessions (assignment_id, start_at, end_at);

CREATE INDEX idx_attendance_sessions_class_date
  ON attendance_sessions (class_id, session_date);

CREATE INDEX idx_attendance_sessions_created_by
  ON attendance_sessions (created_by);

CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  session_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  scanned_at TIMESTAMPTZ(6) NOT NULL,
  status attendance_status NOT NULL,
  late_minutes INTEGER,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT pk_attendance_records PRIMARY KEY (id),
  CONSTRAINT uq_attendance_records_session_student UNIQUE (session_id, student_id),
  CONSTRAINT chk_attendance_records_late_minutes
    CHECK (late_minutes IS NULL OR late_minutes >= 0),
  CONSTRAINT fk_attendance_records_session
    FOREIGN KEY (session_id)
    REFERENCES attendance_sessions (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_records_student
    FOREIGN KEY (student_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_attendance_records_student_scanned
  ON attendance_records (student_id, scanned_at);

CREATE INDEX idx_attendance_records_session_status
  ON attendance_records (session_id, status);

COMMIT;
